### ISSUE TITLE
Dependency on ActiveSupport >= 4.2

### ISSUE THREAD

**Issue by daemonsy** [yuki24/artemis#65]
Hi @yuki24. We are using Artemis but have some applications that are relying on Rails 4.0.x (with sourced LTS support). 

Artemis requires `>= 4.2`. Is there anything specific in the API that requires above 4.2? 

Is there any chance this can be relaxed? 

Thanks.

**Comment by yuki24** [comment]
Rails 4.0 and 4.1 are both very old, and in my experience it requires a significant amount of time to maintain the compatibility. But I'm open to relaxing it if you could give it a shot, set up Travis builds and get the builds green.

**Comment by daemonsy** [comment]
Thank you very much, I'll give it a shot.

**Comment by daemonsy** [comment]
I got green build on my fork, hopefully this works. 
https://github.com/yuki24/artemis/pull/66

**Comment by daemonsy** [comment]
Update: Rails 4.0 probably won't work without some code changes. 
PR to revert the changes: https://github.com/yuki24/artemis/pull/67

**Comment by yuki24** [comment]
[The build for Rails 4.1](https://travis-ci.org/yuki24/artemis/jobs/540494735) has been fixes and there's only [one failure in the build for Rails 4.0](https://travis-ci.org/yuki24/artemis/jobs/540494736), so I feel pretty good about the current state. I'm going to cut a new release.

**Comment by yuki24** [comment]
released as https://github.com/yuki24/artemis/releases/tag/v0.5.0

**Comment by daemonsy** [comment]
Thank you! :pray:
