### ISSUE TITLE
Using multiple clients with test fixtures

### ISSUE THREAD

**Issue by JanStevens** [yuki24/artemis#68]
Hello,

I have 3 different clients that all implement a GraphQL query called `query_events`, with the current test setup and assumptions I can't figure out how I should separate them in the fixtures directory. Ideally I would like to have the following structure (following the operations pattern):

```
fixtures/graphql/client_1/query_events.yml
fixtures/graphql/client_2/query_events.yml
fixtures/graphql/client_3/query_events.yml
```

Right now I have one `query_events.yml` file that contains the responses for all 3 clients but thats not really a clean seperation

**Comment by yuki24** [comment]
Thanks for reporting again. You are right, each service should be able to use its own fixtures.

**Comment by yuki24** [comment]
fixes have been released as https://github.com/yuki24/artemis/releases/tag/v0.5.1
