### ISSUE TITLE
Load the GraphQL log subscriber automatically

### ISSUE THREAD

**Issue by yuki24** [yuki24/artemis#8]
On Rails it should be safe to auto-require [the log subscriber](https://github.com/github/graphql-client/blob/a0f782c6edccdebdaaf31020b4597331675239ad/lib/graphql/client/log_subscriber.rb#L15-L16
): 
```
require "graphql/client/log_subscriber"
GraphQL::Client::LogSubscriber.attach_to :graphql
```

**Comment by yuki24** [comment]
The graphql-client` gem [already does this](https://github.com/github/graphql-client/blob/399f3fdb4e3c5ff3909557ed4dbfccde7ee53907/lib/graphql/client/railtie.rb#L19-L22), I wonder if Artemis should dup it.

**Comment by jonallured** [comment]
Or I guess we could just require the railtie?

```
require "graphql/client/railtie"
```

**Comment by jonallured** [comment]
Would it be surprising for Artemis to require the railtie of the gem it sits on top of?

**Comment by yuki24** [comment]
Requiring the entire `"graphql/client/railtie"` would probably be surprising if you already know you have to opt-in to active the [Rails ERB integration](https://github.com/github/graphql-client#rails-erb-integration).

I think it should be fine to load just the log subscriber. It is documented as a public API so it shouldn't be surprizing (though their README should probably mention that to reduce confusion.) My only concern is double-attaching, but we should be able to work around that by checking the existence of the `GraphQL::Client::LogSubscriber`.

**Comment by yuki24** [comment]
done by c4b71bd18ef547362dc0239f116fd208627c8eca
