### ISSUE TITLE
Add support for newer versions of graphql >= 2.1

### ISSUE THREAD

**Issue by saida** [yuki24/artemis#86]
Hi,

Thanks for this great gem! We'd like to update our graphql gem to `2.1.3`, but artemis depends on the older versions of graphql `< 2.1`. Do you have any plans to update this dependency?

**Comment by eapache-opslevel** [comment]
As of about 20 minutes ago there is finally an updated version of the `graphql-client` gem that supports newer `graphql-ruby` versions (https://github.com/github/graphql-client/pull/314#issuecomment-1908780304).

So this should be possible finally.

**Comment by saida** [comment]
That's great news, thank you!
