### ISSUE TITLE
Initializer `graphql.client.preload` fails to load in Rails 7.0

### ISSUE THREAD

**Issue by arthurchui** [yuki24/artemis#93]
After upgrading Raiils 6.1 to 7.0, the app fails to boot because the [initializer](https://github.com/yuki24/artemis/blob/b314f25059ba912805d2c1ab718f261e81caacbc/lib/artemis/railtie.rb#L60-L72) `graphql.client.preload` cannot load the registered service.

```
/app/app/lib/my_graphql.rb:1:in `<main>': uninitialized constant GraphqlClient (NameError)

class MyGraphql < GraphqlClient
^^^^^^^^^^^^^
Did you mean?  GraphQL
from <internal:/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
from <internal:/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
from /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
from /app/vendor/bundle/ruby/3.2.0/gems/artemis-0.8.0/lib/artemis/railtie.rb:64:in `block (2 levels) in <class:Railtie>'
from /app/vendor/bundle/ruby/3.2.0/gems/artemis-0.8.0/lib/artemis/railtie.rb:62:in `each'
from /app/vendor/bundle/ruby/3.2.0/gems/artemis-0.8.0/lib/artemis/railtie.rb:62:in `block in <class:Railtie>'
from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8.1/lib/rails/initializable.rb:32:in `instance_exec'
```

Note that we expect the code to be autoloaded from `app/lib/*`:
```
# app/lib/my_graphql.rb
class MyGraphql < GraphqlClient
 ...
end

# app/lib/graphql_client.rb
class GraphqlClient < Artemis::Client # base class
  ...
end
```

I do not understand the purpose of the initializer `graphql.client.preload`. Perhaps it can be omitted as the autoloader can load the registered services automatically.

**Comment by yuki24** [comment]
There seems to be a naming convention difference between `GraphqlClient` and `app/lib/graph_client.rb` (notice the `ql` in the class name), and the default file loader may have changed from the classic loader to Zeitwerk as part of the Rails upgrade. Would you mind double-checking the spelling and naming conventions?

The preloader is required in production because class loading in Rails is not thread-safe. Not loading all the constants during the initialization phase may result in degraded performance and/or racing condition when 2 or more threads attempt to load the same class at the same time.

**Comment by yuki24** [comment]
@arthurchui Do you have any updates on this? I would like to help but let me know if you are okay with closing it if you have solved your problem.

**Comment by arthurchui** [comment]
Hi @yuki24 , thanks for your response. It is my fault that I made a typo in the description. I have just fixed it.

**Comment by yuki24** [comment]
@arthurchui I have tweaked the loader and now it should work both with the classic loader and zeitwerk. The version [`v1.0.2`](https://rubygems.org/gems/artemis/versions/1.0.2) includes this fix. Could you give it a try and see if it fixes it?

**Comment by arthurchui** [comment]
@yuki24, it works. Thank you!!
