### ISSUE TITLE
Client initialization with custom Bearer token

### ISSUE THREAD

**Issue by thibgn** [yuki24/artemis#97]
Hey Yuki 👋 

First congrats on this gem! I love the way you implemented it and it'll be a ton of help when I'll get this to work :)

I have an issue with the bearer token I'm trying to use in my requests as it feels like it's not included in the headers.

I created the class, query and config files following the convention from the doc.

```rb
class MyApi < Artemis::Client
  before_execute do |_document, _operation_name, _variables, context|
    token = context[:variables][:token]
    context[:headers] = {
      Authorization: "Bearer #{token}"
    }
  end
end
```

Since I need my client to use the current_user access token each request, I'm using the client like this : 

```rb
# at first I tried this but that wasn't working either :
# client = MyApi.new(context: { headers: { Authorization: "Bearer #{current_user.access_token}" } })
client = MyApi.new(variables: { token: current_user.access_token.to_s })
client.my_query
``` 

In my other app, for the initialization of the client to work I need to disable the doorkeeper verification. When I don't and `byebug` the doorkeeper method, I don't see anything in my headers :

<img width="1012" alt="image" src="https://github.com/user-attachments/assets/5b4f9da2-e75a-4d15-afa4-d8f04911656b">

The actual query does work though, which means that the `before_execute` callback works.

There is probably something I'm doing wrong but I can't put my finger on it 😞 

Thank you for your help!

**Comment by yuki24** [comment]
Apologies for the delay. I know you have closed this PR, but have you tried `with_context`? Something along the lines of:

```ruby
client = MyApi.with_context(token: current_user.access_token.to_s)
client.my_query
```

**Comment by thibgn** [comment]
It was actually the missing `schema` that triggered a request to the API that wouldn't use the `before_execute` callback.
I ended up importing the schema and everything is working perfectly now. Thanks !
